package cloudcli

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"time"
)

var configProductID = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$`)
var configDeploymentID = regexp.MustCompile(`^dep_[A-Za-z0-9_-]{32}$`)
var configEnrollmentToken = regexp.MustCompile(`^enr_[A-Za-z0-9_-]{43}$`)

func connectInstance(ctx context.Context, c *Client, id, output string, out io.Writer) error {
	if !configDeploymentID.MatchString(id) || output == "" {
		return errors.New("需要有效的 --deployment 和新的 --output config.yml 路径")
	}
	if _, err := os.Lstat(output); !errors.Is(err, os.ErrNotExist) {
		return errors.New("输出配置已存在或无法检查，请使用新路径")
	}
	raw, err := c.JSON(ctx, "GET", "/deployments/"+id, nil)
	if err != nil {
		return err
	}
	var d deploymentResponse
	if json.Unmarshal(raw, &d) != nil || d.ID != id || d.Status != "active" || d.Revision < 1 || len(d.Products) < 1 || len(d.Products) > 16 {
		return &TransportError{Message: "部署响应无效或已吊销"}
	}
	seen := make(map[string]bool)
	for _, product := range d.Products {
		if !configProductID.MatchString(product.ProductID) || seen[product.ProductID] {
			return &TransportError{Message: "部署商品列表无效"}
		}
		seen[product.ProductID] = true
	}
	connectionBytes := make([]byte, 24)
	if _, err = rand.Read(connectionBytes); err != nil {
		return errors.New("无法生成本机连接标识")
	}
	connection := "cnx_" + base64.RawURLEncoding.EncodeToString(connectionBytes)
	raw, err = c.JSON(ctx, "POST", "/deployments/"+id+"/enrollments", map[string]int64{"revision": d.Revision})
	if err != nil {
		return err
	}
	defer clear(raw)
	var e enrollmentResponse
	if json.Unmarshal(raw, &e) != nil || e.DeploymentID != id || e.Revision != d.Revision || !configEnrollmentToken.MatchString(e.Token) || !time.Now().Before(e.ExpiresAt) {
		return &TransportError{Message: "登记凭据响应无效"}
	}
	var config bytes.Buffer
	fmt.Fprintf(&config, "# Generated by klib instances connect. Keep this file private.\ndeployment: %q\nconnection: %q\nenrollment-token: %q\nproducts:\n", id, connection, e.Token)
	for _, p := range d.Products {
		fmt.Fprintf(&config, "  - %q\n", p.ProductID)
	}
	defer clear(config.Bytes())
	if err = WritePrivateNew(output, config.Bytes()); err != nil {
		return fmt.Errorf("登记凭据已签发但配置未保存，请重新签发并等待旧凭据到期：%w", err)
	}
	return json.NewEncoder(out).Encode(map[string]any{"ok": true, "deployment_id": id, "connection_id": connection, "revision": d.Revision, "output_file": output, "expires_at": e.ExpiresAt, "state": "waiting_for_instance"})
}
